package com.promptguard.detector.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * JPA entity that persists every prompt analysis result to the database.
 */
@Entity
@Table(name = "prompt_analysis_log")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PromptAnalysisLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Raw prompt text submitted by the caller. */
    @Column(name = "prompt_text", columnDefinition = "TEXT", nullable = false)
    private String promptText;

    /** Calculated risk score 0–100. */
    @Column(name = "risk_score", nullable = false)
    private int riskScore;

    /** HIGH / MEDIUM / LOW */
    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", nullable = false)
    private RiskLevel riskLevel;

    /**
     * Comma-separated list of detected threat category display names.
     * Stored as a single TEXT column for simplicity; an @ElementCollection
     * could be used for full normalisation.
     */
    @Column(name = "detected_threats", columnDefinition = "TEXT")
    private String detectedThreats;

    /** Human-readable explanation generated by the AI analysis engine. */
    @Column(name = "explanation", columnDefinition = "TEXT")
    private String explanation;

    /** UTC timestamp of the analysis. */
    @Column(name = "analyzed_at", nullable = false)
    private LocalDateTime analyzedAt;

    /** Optional caller identifier (IP address, API key prefix, etc.). */
    @Column(name = "caller_id")
    private String callerId;
}
